let irregularVerbsList = [
	['irr_быть', 'be, was/were, been'],
	['irr_бить', 'beat, beat, beaten'],
	['irr_становиться', 'become, became, become'],
	['irr_начинать', 'begin, began, begun'],
	['irr_кусать', 'bite, bit, bitten'],
	['irr_дуть', 'blow, blew, blown'],
	['irr_ломать', 'break, broke, broken'],
	['irr_приносить', 'bring, brought, brought'],
	['irr_строить', 'build, built, built'],
	['irr_покупать', 'buy, bought, bought'],
	['irr_ловить', 'catch, caught, caught'],
	['irr_выбирать', 'choose, chose, chosen'],
	['irr_приходить', 'come, came, come'],
	['irr_стоить', 'cost, cost, cost'],
	['irr_резать', 'cut, cut, cut'],
	['irr_делать', 'do, did, done'],
	['irr_рисовать', 'draw, drew, drawn'],
	['irr_пить', 'drink, drank, drunk'],
	['irr_водить машину', 'drive, drove, driven'],
	['irr_есть', 'eat, ate, eaten'],
	['irr_падать', 'fall, fell, fallen'],
	['irr_чувствовать', 'feel, felt, felt'],
	['irr_бороться', 'fight, fought, fought'],
	['irr_находить', 'find, found, found'],
	['irr_летать', 'fly, flew, flown'],
	['irr_забывать', 'forget, forgot, forgotten'],
	['irr_получать', 'get, got, got'],
	['irr_давать', 'give, gave, given'],
	['irr_направляться', 'go, went, gone'],
	['irr_расти', 'grow, grew, grown'],
	['irr_вешать', 'hang, hung, hung'],
	['irr_иметь', 'have, had, had'],
	['irr_слышать', 'hear, heard, heard'],
	['irr_прятать', 'hide, hid, hidden'],
	['irr_попадать в цель', 'hit, hit, hit'],
	['irr_держать', 'hold, held, held'],
	['irr_причинять боль', 'hurt, hurt, hurt'],
	['irr_хранить', 'keep, kept, kept'],
	['irr_знать', 'know, knew, known'],
	['irr_оставлять', 'leave, left, left'],
	['irr_давать в долг', 'lend, lent, lent'],
	['irr_позволять', 'let, let, let'],
	['irr_лежать', 'lie, lay, lain'],
	['irr_освещать', 'light, lit, lit'],
	['irr_терять', 'lose, lost, lost'],
	['irr_производить', 'make, made, made'],
	['irr_значить', 'mean, meant, meant'],
	['irr_встречать', 'meet, met, met'],
	['irr_платить', 'pay, paid, paid'],
	['irr_ставить', 'put, put, put'],
	['irr_читать', 'read, read, read'],
	['irr_ездить верхом', 'ride, rode, ridden'],
	['irr_звенеть', 'ring, rang, rung'],
	['irr_подниматься', 'rise, rose, risen'],
	['irr_бежать', 'run, ran, run'],
	['irr_говорить', 'say, said, said'],
	['irr_видеть', 'see, saw, seen'],
	['irr_продавать', 'sell, sold, sold'],
	['irr_посылать', 'send, sent, sent'],
	['irr_светить', 'shine, shone, shone'],
	['irr_стрелять', 'shoot, shot, shot'],
	['irr_показывать', 'show, showed, shown'],
	['irr_закрывать', 'shut, shut, shut'],
	['irr_петь', 'sing, sang, sung'],
	['irr_сидеть', 'sit, sat, sat'],
	['irr_спать', 'sleep, slept, slept'],
	['irr_говорить', 'speak, spoke, spoken'],
	['irr_тратить', 'spend, spent, spent'],
	['irr_стоять', 'stand, stood, stood'],
	['irr_красть', 'steal, stole, stolen'],
	['irr_плавать', 'swim, swam, swum'],
	['irr_брать, взять', 'take, took, taken'],
	['irr_учить', 'teach, taught, taught'],
	['irr_рвать', 'tear, tore, torn'],
	['irr_рассказывать', 'tell, told, told'],
	['irr_думать', 'think, thought, thought'],
	['irr_бросать', 'throw, threw, thrown'],
	['irr_понимать', 'understand, understood, understood'],
	['irr_просыпаться', 'wake, woke, woken'],
	['irr_носить одежду', 'wear, wore, worn'],
	['irr_побеждать', 'win, won, won'],
	['irr_писать', 'write, wrote, written']
];

let verbsList = [
	['ver_принимать', 'accept'],
	['ver_признавать', 'admit'],
	['ver_советовать', 'advise'],
	['ver_соглашаться', 'agree'],
	['ver_позволять', 'allow'],
	['ver_развлекать', 'amuse'],
	['ver_раздражать', 'annoy'],
	['ver_отвечать', 'answer'],
	['ver_извиняться', 'apologize'],
	['ver_приехать', 'arrive'],
	['ver_спрашивать', 'ask'],
	['ver_привлекать', 'attract'],
	['ver_бороться', 'battle'],
	['ver_верить', 'believe'],
	['ver_краснеть', 'blush'],
	['ver_занимать', 'borrow'],
	['ver_гудеть', 'buzz'],
	['ver_звонить', 'call'],
	['ver_мочь', 'can'],
	['ver_отменить', 'cancel'],
	['ver_нести', 'carry'],
	['ver_менять', 'change'],
	['ver_требовать', 'claim'],
	['ver_чистить', 'clean'],
	['ver_закрывать', 'close'],
	['ver_собирать', 'collect'],
	['ver_расчесывать', 'comb'],
	['ver_общаться', 'communicate'],
	['ver_жаловаться', 'complain'],
	['ver_готовить', 'cook'],
	['ver_копировать', 'copy'],
	['ver_кашлять', 'cough'],
	['ver_танцевать', 'dance'],
	['ver_решать', 'decide'],
	['ver_обсуждать', 'discuss'],
	['ver_наслаждаться', 'enjoy'],
	['ver_объяснять', 'explain'],
	['ver_заполнить', 'fill'],
	['ver_заканчивать', 'finish'],
	['ver_соответствовать', 'fit'],
	['ver_фиксировать', 'fix'],
	['ver_следовать', 'follow'],
	['ver_светиться', 'glow'],
	['ver_схватить', 'grip'],
	['ver_управлять', 'handle'],
	['ver_случаться', 'happen'],
	['ver_помогать', 'help'],
	['ver_нравиться', 'like'],
	['ver_слушать', 'listen'],
	['ver_жить', 'live'],
	['ver_выглядеть', 'look'],
	['ver_двигать', 'move'],
	['ver_нуждаться', 'need'],
	['ver_открывать', 'open'],
	['ver_организовывать', 'organise'],
	['ver_играть', 'play'],
	['ver_обещать', 'promise'],
	['ver_литься', 'rain'],
	['ver_ответить', 'reply'],
	['ver_подписывать', 'sign'],
	['ver_курить', 'smoke'],
	['ver_произносить по буквам', 'spell'],
	['ver_oстанавливать', 'stop'],
	['ver_учиться', 'study'],
	['ver_быть успешным', 'succeed'],
	['ver_предлагать', 'suggest'],
	['ver_говорить', 'talk'],
	['ver_переводить', 'translate'],
	['ver_путешествовать', 'travel'],
	['ver_пытаться', 'try'],
	['ver_печатать', 'type'],
	['ver_использовать', 'use'],
	['ver_ждать', 'wait'],
	['ver_хотеть', 'want'],
	['ver_смотреть', 'watch'],
	['ver_махать', 'wave'],
	['ver_работать', 'work'],
	['ver_беспокоиться', 'worry']
];

let adverbsList = [
	['adv_наверху','above'],
	['adv_случайно','accidentally'],
	['adv_соответственно','according'],
	['adv_фактически','actually'],
	['adv_опять','again'],
	['adv_почти','almost'],
	['adv_уже','already'],
	['adv_также','also'],
	['adv_всегда','always'],
	['adv_высокомерно','arrogantly'],
	['adv_плохо','badly'],
	['adv_красиво','beautifully'],
	['adv_до','before'],
	['adv_ниже','below'],
	['adv_кроме того','besides'],
	['adv_вслепую','blindly'],
	['adv_хвастливо','boastfully'],
	['adv_кратко','briefly'],
	['adv_ярко','brightly'],
	['adv_широко','broadly'],
	['adv_тщательно','carefully'],
	['adv_осторожно','cautiously'],
	['adv_конечно','certainly'],
	['adv_ясно','clearly'],
	['adv_умно','cleverly'],
	['adv_красочно','colourfully'],
	['adv_обычно','commonly'],
	['adv_правильно','correctly'],
	['adv_смело','courageously'],
	['adv_ежедневно','daily'],
	['adv_изящно','daintily'],
	['adv_обманчиво','deceivingly'],
	['adv_глубоко','deeply'],
	['adv_вызывающе','defiantly'],
	['adv_восхитительно','delightfully'],
	['adv_сомнительно','doubtfully'],
	['adv_мечтательно','dreamily'],
	['adv_легко','easily'],
	['adv_энергично','energetically'],
	['adv_с энтузиазмом','enthusiastically'],
	['adv_одинаково','equally'],
	['adv_особенно','especially'], 
	['adv_даже','even'],
	['adv_равномерно','evenly'], 
	['adv_в конце концов','eventually'], 
	['adv_когда-либо','ever'],
	['adv_точно','exactly'],
	['adv_взволнованно','excitedly'], 
	['adv_нежно','fondly'], 
	['adv_глупо','foolishly'], 
	['adv_к счастью','fortunately'], 
	['adv_вперед','forward'], 
	['adv_дружелюбно','friendly'], 
	['adv_жадно','greedily'], 
	['adv_счастливо','happily'], 
	['adv_с торудом','hardly'], 
	['adv_честно','honestly'],
	['adv_в самом деле','indeed'], 
	['adv_невинно','innocently'], 
	['adv_внутри','inside'], 
	['adv_вместо','instead'], 
	['adv_справедливо','justly'], 
	['adv_любезно','kindly'], 
	['adv_недавно','lately'], 
	['adv_лениво','lazily'], 
	['adv_меньше','less'], 
	['adv_свободно','loosely'], 
	['adv_громко','loudly'], 
	['adv_безумно','madly'], 
	['adv_около','nearly'], 
	['adv_никогда','never'], 
	['adv_изредка','occasionally'], 
	['adv_часто','often'], 
	['adv_раз','once'], 
	['adv_только','only'],
	['adv_отлично','perfectly'],	
	['adv_возможно','perhaps'],	
	['adv_вежливо','politely'],	
	['adv_вероятно','probably'],	
	['adv_быстро','quickly'],	
	['adv_нечасто','rarely'],	
	['adv_довольно','rather'],	
	['adv_действительно','really'],	
	['adv_регулярно','regularly'],	
	['adv_редко','seldom'],	
	['adv_серьезно','seriously'],	
	['adv_медленно','slowly'],	
	['adv_как-то','somehow'],	
	['adv_иногда','sometimes'],	
	['adv_где-то','somewhere'],	
	['adv_скоро','soon'],	
	['adv_насквозь','through'],	
	['adv_таким образом','thus'],	
	['adv_сегодня','today'],	
	['adv_завтра','tomorrow'],	
	['adv_очень','very'],	
	['adv_тепло','warmly'],	
	['adv_слабо','weakly'],	
	['adv_вчера','yesterday']
];

let phrasalVerbsList = [
	['phv_отступать', 'back away'],
	['phv_возвращаться', 'be back'],
	['phv_покидать', 'be off'],
	['phv_отсутствовать', 'be out'],
	['phv_окончиться', 'be over'],
	['phv_собираться', 'be up to'],
	['phv_разбиться вдребезги', 'blow out'],
	['phv_взорвать', 'blow up'],
	['phv_сломаться', 'break down'],
	['phv_разрывать отношения', 'break up'],
	['phv_перезвонить', 'call back'],
	['phv_отозвать', 'call off'],
	['phv_успокоиться', 'calm down'],
	['phv_носить с собой', 'carry around'],
	['phv_продолжаться', 'carry on'],
	['phv_осуществлять', 'carry out'],
	['phv_переносить', 'carry over'],
	['phv_регистрироваться', 'check in'],
	['phv_прибираться', 'clean up'],
	['phv_натолкнуться', 'come across'],
	['phv_идти вместе', 'come along'],
	['phv_происходить из', 'come from'],
	['phv_войдите', 'come in'],
	['phv_отрываться', 'come off'],
	['phv_давай!', 'come on'],
	['phv_приходить', 'come over'],
	['phv_рассчитывать на', 'count on'],
	['phv_отрезать', 'cut off'],
	['phv_закончить', 'end up'],
	['phv_выяснить', 'figure out'],
	['phv_обнаружить', 'find out'],
	['phv_преодолеть', 'get around'],
	['phv_перезванивать', 'get back'],
	['phv_спускаться', 'get down'],
	['phv_ладить', 'get on'],
	['phv_выбираться', 'get out'],
	['phv_справиться', 'get over'],
	['phv_вставать', 'get up'],
	['phv_сдаваться', 'give up'],
	['phv_уходить', 'go away'],
	['phv_входить', 'go in'],
	['phv_продолжать', 'go on'],
	['phv_выйти', 'go out'],
	['phv_пройти через', 'go through'],
	['phv_подниматься', 'go up'],
	['phv_вырастать', 'grow up'],
	['phv_вешать трубку', 'hang up'],
	['phv_протягивать', 'hold out'],
	['phv_поднимать', 'hold up'],
	['phv_поддерживать', 'keep up'],
	['phv_впустить', 'let in'],
	['phv_выпускать', 'let out'],
	['phv_лечь', 'lie down'],
	['phv_искать', 'look for'],
	['phv_предвкушать', 'look forward to'],
	['phv_высматривать', 'look out'],
	['phv_просматривать', 'look over'],
	['phv_составить', 'make up'],
	['phv_въехать', 'move in'],
	['phv_идти дальше', 'move on'],
	['phv_взять', 'pick up'],
	['phv_указывать', 'point out'],
	['phv_натягивать', 'pull on'],
	['phv_останавливать ...', 'pull up'],
	['phv_отказаться от мысли', 'put away'],
	['phv_опустить', 'put down'],
	['phv_вставить', 'put in'],
	['phv_надеть', 'put on'],
	['phv_строить', 'put up'],
	['phv_убегать', 'run away'],
	['phv_столкнуться', 'run into'],
	['phv_сбегать', 'run off'],
	['phv_высаживать', 'set down'],
	['phv_поселяться', 'settle down'],
	['phv_появляться', 'show up'],
	['phv_закрыть', 'shut down'],
	['phv_заставить замолчать', 'shut up'],
	['phv_садиться', 'sit down'],
	['phv_приподняться', 'sit up'],
	['phv_рассыпаться', 'spread out'],
	['phv_быть наготове', 'stand by'],
	['phv_вставать', 'stand up'],
	['phv_включить питание', 'switch on'],
	['phv_забирать', 'take away'],
	['phv_взять обратно', 'take back'],
	['phv_взлететь', 'take off'],
	['phv_приобретать', 'take on'],
	['phv_вынимать', 'take out'],
	['phv_перенимать', 'take over'],
	['phv_превращаться', 'turn into'],
	['phv_выключить', 'turn off'],
	['phv_включaть', 'turn on'],
	['phv_оказаться', 'turn out'],
	['phv_переворачивать', 'turn over'],
	['phv_проснуться', 'wake up'],
	['phv_входить без ведома', 'walk in'],
	['phv_легко побеждать', 'walk over'],
	['phv_обрабатывать', 'work up'],
	['phv_записывать', 'write down']
];

let adjectivesList = [
	['adj_боящийся', 'afraid'],
	['adj_живой', 'alive'],
	['adj_сердитый', 'angry'],
	['adj_отвратительный', 'awful'],
	['adj_плохой', 'bad'],
	['adj_красивый', 'beautiful'],
	['adj_большой', 'big'],
	['adj_скучающий', 'bored'],
	['adj_храбрый', 'brave'],
	['adj_яркий', 'bright'],
	['adj_сломанный', 'broken'],
	['adj_занятый', 'busy'],
	['adj_спокойный', 'calm'],
	['adj_осторожный', 'careful'],
	['adj_чистый', 'clean'],
	['adj_ясный', 'clear'],
	['adj_умный', 'clever'],
	['adj_холодный', 'cold'],
	['adj_удобный', 'comfortable'],
	['adj_сумасшедший', 'crazy'],
	['adj_жестокий', 'cruel'],
	['adj_любопытный', 'curious'],
	['adj_опасный', 'dangerous'],
	['adj_темный', 'dark'],
	['adj_мертвый', 'dead'],
	['adj_подавленный', 'depressed'],
	['adj_определенный', ' determined'],
	['adj_другой', 'different'],
	['adj_трудный', 'difficult'],
	['adj_грязный', 'dirty'],
	['adj_нарушенный', 'disturbed'],
	['adj_сухой', 'dry'],
	['adj_ранний', 'early'],
	['adj_легкий', 'easy'],
	['adj_смущенный', 'embarrassed'],
	['adj_восторженный', 'enthusiastic'],
	['adj_злой', 'evil'],
	['adj_взволнованный', 'excited'],
	['adj_ложный', 'false'],
	['adj_известный', 'famous'],
	['adj_быстрый', 'fast'],
	['adj_прекрасный', 'fine'],
	['adj_безрассудный', 'foolish'],
	['adj_свежий', 'fresh'],
	['adj_дружелюбный', 'friendly'],
	['adj_смешной', 'funny'],
	['adj_хороший', 'good'],
	['adj_счастливый', 'happy'],
	['adj_тяжелый', 'hard'],
	['adj_здоровый', 'healthy'],
	['adj_пронзительный', 'high-pitched'],
	['adj_горячий', 'hot'],
	['adj_огромный', 'huge'],
	['adj_голодный', 'hungry'],
	['adj_важный', 'important'],
	['adj_невозможный', 'impossible'],
	['adj_крупный', 'large'],
	['adj_поздний', 'late'],
	['adj_небольшой', 'little'],
	['adj_одинокий', 'lonely'],
	['adj_длинный', 'long'],
	['adj_громкий', 'loud'],
	['adj_восхитительный', 'lovely'],
	['adj_везучий', 'lucky'],
	['adj_узкий', 'narrow'],
	['adj_новый', 'new'],
	['adj_милый', 'nice'],
	['adj_шумный', 'noisy'],
	['adj_старый', 'old'],
	['adj_идеальный', 'perfect'],
	['adj_приятный', 'pleasant'],
	['adj_бедный', 'poor'],
	['adj_гордый', 'proud'],
	['adj_скорый', 'quick'],
	['adj_тихий', 'quiet'],
	['adj_реальный', 'real'],
	['adj_богатый', 'rich'],
	['adj_безопасный', 'safe'],
	['adj_испуганный', 'scared'],
	['adj_короткий', 'short'],
	['adj_застенчивый', 'shy'],
	['adj_безмолвный', 'silent'],
	['adj_глупый', 'silly'],
	['adj_медленный', 'slow'],
	['adj_маленький', 'small'],
	['adj_мягкий', 'soft'],
	['adj_тупой', 'stupid'],
	['adj_успешный', 'successful'],
	['adj_высокий', 'tall'],
	['adj_вкусный', 'tasty'],
	['adj_ужасный', 'terrible'],
	['adj_крошечный', 'tiny'],
	['adj_уставший', 'tired'],
	['adj_уродливый', 'ugly'],
	['adj_несчастливый', 'unhappy'],
	['adj_слабый', 'weak'],
	['adj_злобный', 'wicked'],
	['adj_широкий', 'wide'],
	['adj_тревожный', 'worried'],
	['adj_молодой', 'young']
];




Array.prototype.deepReverse = function () {
	let temp = [];
	for (let i = 0; i < this.length; i++) {
		temp[i] = this[i].slice();
	}
	temp.map(function(elem) {
		return elem.reverse();
	});
	return temp;
};

Array.prototype.shuffle = function () {
	if (this.length == 1) {
		return this;
	}
	for (var j, x, i = this.length; i; j = Math.floor(Math.random() * i), x = this[--i], this[i] = this[j], this[j] = x);
	return this;
};
